[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "metaheuristic-designer"
version = "0.1.4"
authors = [
    {name = "eugenioLR", email = "eugeniolorente0@gmail.com"}
]
description = "A python package to desing metaheuristic optimization algorithms from components."
readme = "README.md"
requires-python = ">=3.10"
keywords = ["optization", "genetic-algorithm", "evolutionary-algorithms", "metaheuristics"]
license = {text = "LICENSE"}
dependencies = [
    "matplotlib>=3.5",
    "numpy>=1.21",
    "scipy>=1.8",
    "pyparsing>=3.0",
    "scikit-image>=0.21",
]

[project.urls]
Homepage = "https://github.com/eugenioLR/metaheuristic-designer"

[project.optional-dependencies]
dev = [
    "nox>=2023.4.22",
    "pytest>=7.4.0",
    "coverage>=7.3.1",
    "sphinx_material>=0.0.36",
    "sphinx>=7.1.1",
    "pygame>=2.5.0",    
    "networkx>=3.1",
    "opencv-python>=4.8"
]

examples = [
    "pygame>=2.5.0",    
    "networkx>=3.1",
    "opencv-python>=4.8"
]

